name: SauceDemo Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4

      - name: Zainstaluj .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Przywróć zależności
        run: dotnet restore

      - name: Zbuduj projekt
        run: dotnet build --no-restore

      - name: Zainstaluj przeglądarki Playwright
        run: dotnet tool install --global Microsoft.Playwright.CLI && playwright install --with-deps chromium

      - name: Uruchom testy
        run: dotnet test --no-build --logger "trx;LogFileName=results.trx" --results-directory reports/

      - name: Publikuj raport z testów
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: reports/results.trx

      - name: Podsumowanie testów na GitHub
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: reports/results.trx